---
- name: Create the network configuration files for slaves of the bond devices
  template:
    src: "bond_slave_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/{{ network_interface_file_prefix }}{{ item.1 }}{{ network_interface_file_postfix }}"
  with_subelements:
    - "{{ network_bond_interfaces }}"
    - bond_slaves
  when: not item.1 in network_ether_interfaces|map(attribute='device')|list and
        not item.1 in network_bridge_interfaces|map(attribute='device')|list and
        not item.1 in network_vlan_interfaces|map(attribute='device')|list
  register: bond_port_result
  notify: restart networking

- name: Create the network configuration files for bond devices
  template:
    src: "bond_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/{{ network_interface_file_prefix }}{{ item.device }}{{ network_interface_file_postfix }}"
  loop: "{{ network_bond_interfaces }}"
  register: bond_result
  notify: restart networking

- name: Make sure the bonding module is loaded
  modprobe:
    name: bonding
    state: present
  when: bond_result is changed
  notify: restart networking

- name: Make the bonding module persistent
  become: true
  lineinfile:
    line: 'bonding'
    dest: /etc/modules
    insertafter: EOF
  when:
    - network_modprobe_persist
  notify: restart networking
