---
- name: Install the required packages in Debian derivatives
  apt:
    name: "{{ network_pkgs }}"
    state: present
  environment: "{{ env }}"
  when: network_check_packages

- name: Make sure the include line is the only line in interfaces file
  copy:
    content: |
      #
      # Managed by ansible
      #

      source {{ net_path }}/*
    dest: /etc/network/interfaces
  when: network_configured_interfaces_only
  notify: restart networking

- name: Make sure the source include line is there in interfaces file
  lineinfile:
    regexp: '^source\s{{ net_path | regex_escape() }}/\*'
    line: "source {{ net_path }}/*"
    dest: /etc/network/interfaces
    state: present
    insertafter: EOF
  when: not network_configured_interfaces_only | bool

- name: Make sure the source-directory include line is not there in interfaces file
  lineinfile:
    regexp: '^source-directory\s{{ net_path | regex_escape() }}/?'
    dest: /etc/network/interfaces
    state: absent
  when: not network_configured_interfaces_only | bool

- name: Create the directory for interface cfg files
  file:
    path: "{{ net_path }}"
    state: directory
