---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define network_pkgs.
  set_fact:
    network_pkgs: "{{ _network_pkgs }}"
  when: network_pkgs is not defined

- name: Include specific tasks for the OS family
  include_tasks: "{{ ansible_os_family }}_initial.yml"

- name: Cleanup interfaces configuration
  import_tasks: "clean_interfaces.yml"
  when: network_configured_interfaces_only

- name: Configure Ethernet interfaces
  import_tasks: "ether_interfaces.yml"
  when: network_ether_interfaces | length > 0

- name: Configure Bond interfaces
  import_tasks: "bond_interfaces.yml"
  when: network_bond_interfaces | length > 0

- name: Configure VLAN interfaces
  import_tasks: "vlan_interfaces.yml"
  when: network_vlan_interfaces | length > 0

- name: Configure Bridge interfaces
  import_tasks: "bridge_interfaces.yml"
  when: network_bridge_interfaces | length > 0
