---
- name: Install the required packages in Redhat derivatives
  yum:
    name: "{{ network_pkgs }}"
    state: present
  when: network_check_packages

- name: Write configuration files for rhel route configuration with vlan
  template:
    src: "route_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/route-{{ item.device }}"
  loop: "{{ network_vlan_interfaces }}"
  when: network_vlan_interfaces != [] and item.route is defined

- name: Write configuration files for rhel route configuration
  template:
    src: "route_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/route-{{ item.device }}"
  loop: "{{ network_ether_interfaces }}"
  when: network_ether_interfaces != [] and item.route is defined

- name: Write configuration files for route configuration
  template:
    src: "route_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/route-{{ item.device }}"
  loop: "{{ network_bond_interfaces }}"
  when: network_bond_interfaces != [] and item.route is defined

- name: Write configuration files for rhel route configuration
  template:
    src: "route_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/route-{{ item.device }}"
  loop: "{{ network_bridge_interfaces }}"
  when: network_bridge_interfaces != [] and item.route is defined

- name: Cleanup gateway dev that is not set to the one we want
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: "^GATEWAYDEV=(?!{{ gateway_dev }})"
    state: absent
  when: gateway_dev is defined

- name: Explicitly set the gateway device
  lineinfile:
    dest: /etc/sysconfig/network
    line: "GATEWAYDEV={{ gateway_dev }}"
  when: gateway_dev is defined
